### ISSUE TITLE
Trying to solve design issues with Observables2

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaGizmos/Observables.jl#47]
I'd like some input on my redesign idea https://github.com/jkrumbiegel/Observables2.jl

I've noticed that in Makie, it gets quite problematic that observables don't tell you who they are listening to. That means you can't disconnect easily and that means often resources are never garbage collected until the whole Scene is destroyed.

I've written my reasoning down in the README and it would be great if those who are interested take a look.

**Comment by timholy** [comment]
I'm a bit confused, because the README says

> every time you create an observable using on

But `on` doesn't (now) create an `Observable`. Perhaps it did when you wrote this? `map` does, is that the problem you're actually concerned about?

As far as the disconnect problem goes, I think we could solve it by having an optional `obsfuncs` field in an Observable and having `map!` store the output of `onany` there.

**Comment by timholy** [comment]
Ah, it looks like #48 solved many of the issues this was proposed to cover (and was submitted after the OP here). Perhaps close? Or leave open to address https://github.com/JuliaGizmos/Observables.jl/pull/48#issuecomment-699608226?

**Comment by jkrumbiegel** [comment]
sorry yeah this has become obsolete :) I'll close it, there wasn't that much room for a redesign after all
