### ISSUE TITLE
[0.4.0] why not keep `connect!` same as 0.3.x, change the docs and make a new func?

### ISSUE THREAD

**Issue by touchft** [JuliaGizmos/Observables.jl#70]
how about make a new function and keep connect! as 0.3.x?
[0.3.x] connect!(x,y) means `x->y`
[0.4.x] plugin!(x,y)/update!(x,y)/transfer!(x,y) means  `y->x`

**Comment by timholy** [comment]
1. Because the old function did the opposite of what it said in the in documentation.
2. The Julia convention is that the modified argument is first. This case is actually ambiguous because while in `connect!(x, y)`, `x` will be lazily-modified whenever `y` is, the way Observables is implemented means the actual change in connectivity is made to `y`. So this argument isn't as definitive as it could be.
3. If people had wanted to preserve the old behavior, they should have submitted a PR to fix the docstring. No one did over years of use.
4. We don't need 2 functions that do the same thing

**Comment by touchft** [comment]
Thank you!
